"""Training/eval run configuration.

Configs are plain YAML under `configs/train/`. Nothing is hardcoded in the
scripts: the config names the condition, the model file, the scale and every
trainer argument, and the whole trainer-argument dict is what MLflow records as
the run's hyperparameters.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from .paths import CONFIG_DIR, REPO_ROOT


@dataclass
class RunConfig:
    """One training run, as read from a config file."""

    path: Path
    run_name: str
    experiment: str
    condition: str
    seed: int
    model: str
    scale: str
    task: str = "detect"
    train: dict[str, Any] = field(default_factory=dict)
    subset: dict[str, int] | None = None

    @property
    def model_path(self) -> Path:
        p = Path(self.model)
        return p if p.is_absolute() else REPO_ROOT / p

    @property
    def data_yaml(self) -> Path:
        """The Ultralytics data yaml generated by scripts/prepare_dataset.py.

        HBB and OBB have separate yamls pointing at separate dataset roots, so
        an oriented label can never reach a detect model or the reverse.
        """
        suffix = "" if self.task == "detect" else "_obb"
        return CONFIG_DIR / "data" / f"dior_{self.condition}{suffix}.yaml"

    def scaled_model(self) -> Path:
        """Insert the scale letter Ultralytics expects: yolo11_x.yaml -> yolo11n_x.yaml.

        Ultralytics picks a scale by finding a single letter in the model stem
        (`yolo11n.yaml` -> n). Our file is `yolo11_dior_hbb.yaml`, which has no
        such marker, so the scale is spliced in after the family name to produce
        `yolo11n_dior_hbb.yaml`. The file need not exist — Ultralytics strips the
        scale letter back off when it resolves the path.
        """
        stem = self.model_path.stem
        family, _, rest = stem.partition("_")
        return self.model_path.with_name(f"{family}{self.scale}_{rest}{self.model_path.suffix}")


def load_run_config(path: str | Path) -> RunConfig:
    path = Path(path)
    if not path.is_absolute():
        path = REPO_ROOT / path
    if not path.exists():
        raise FileNotFoundError(f"config not found: {path}")

    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}

    missing = [k for k in ("run_name", "experiment", "condition", "model", "scale") if k not in raw]
    if missing:
        raise KeyError(f"{path}: missing required key(s): {', '.join(missing)}")

    task = raw.get("task", "detect")
    if task not in {"detect", "obb"}:
        raise ValueError(f"{path}: task must be 'detect' or 'obb', got {task!r}")

    return RunConfig(
        path=path,
        run_name=raw["run_name"],
        experiment=raw["experiment"],
        condition=raw["condition"],
        seed=int(raw.get("seed", 0)),
        model=raw["model"],
        scale=raw["scale"],
        task=task,
        train=dict(raw.get("train") or {}),
        subset=raw.get("subset"),
    )
