"""Verify the Hazy-DIOR release structure and write the pairing report.

    python scripts/check_pairing.py

Exits non-zero if any invariant fails, so it doubles as a guard: run it on a new
machine before anything else and it will tell you whether the release you have
is the release this project was built against.

Writes outputs/verification/pairing_report.md and .json.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.data.pairing import (  # noqa: E402
    SEVERITIES,
    aligned_ids,
    checks_to_dict,
    read_splits,
    run_all,
)
from src.utils.logging import get_logger  # noqa: E402
from src.utils.paths import VERIFICATION_DIR, ensure_dir, load_paths  # noqa: E402
from src.utils.seed import git_commit  # noqa: E402

log = get_logger("check_pairing")


def render_markdown(paths, checks) -> str:
    splits = read_splits(paths)
    ids = aligned_ids(paths)

    lines: list[str] = [
        "# Hazy-DIOR pairing report",
        "",
        f"- Source: `{paths.hazy_dior_root}`",
        f"- Repo commit: `{git_commit(short=True)}`",
        f"- Generated by: `scripts/check_pairing.py`",
        "",
        "## Verdict",
        "",
    ]

    all_passed = all(c.passed for c in checks)
    lines += [
        "**All structural invariants hold.**"
        if all_passed
        else "**AT LEAST ONE INVARIANT FAILED — see the table below.**",
        "",
        "Note what this does and does not mean. It confirms the release has the",
        "structure this project was built against. It does *not* mean Hazy-DIOR",
        "filenames map 1:1 onto clear DIOR filenames — they do not, and the",
        "checks below are what establish that.",
        "",
        "## Checks",
        "",
        "| Check | Result | Detail |",
        "|---|---|---|",
    ]
    for c in checks:
        lines.append(f"| `{c.name}` | {'PASS' if c.passed else 'FAIL'} | {c.detail} |")

    lines += [
        "",
        "## DIOR detection splits (`ImageSets/Main`)",
        "",
        "| Split | Images | First id | Last id |",
        "|---|---|---|---|",
    ]
    for name, values in splits.items():
        lines.append(f"| {name} | {len(values):,} | {values[0]} | {values[-1]} |")

    inv = next(c for c in checks if c.name == "inventory")
    member = next(c for c in checks if c.name == "split_membership")
    renum = next(c for c in checks if c.name == "unaligned_are_renumbered_3x")

    lines += [
        "",
        "## The finding",
        "",
        "The release ships imagery under a *restoration* split whose directory",
        "names collide with, but do not correspond to, DIOR's detection split.",
        "",
        "| Directory | Files | Keyed by |",
        "|---|---|---|",
        f"| `test/{{gt,haze}}/{{thin,moderate,thick}}/` | {len(ids):,} ids | **DIOR ID** |",
        f"| `train/{{gt,haze}}/` | {inv.evidence['train/gt']:,} files "
        f"({inv.evidence['train_unique']:,} unique) | **renumbered 1..N** |",
        f"| `val/{{gt,haze}}/` | {inv.evidence['val/gt']:,} files "
        f"({inv.evidence['val_unique']:,} unique) | **renumbered 1..N** |",
        "",
        f"The partition closes exactly: {inv.evidence['aligned']:,} + "
        f"{inv.evidence['train_unique']:,} + {inv.evidence['val_unique']:,} = "
        f"{inv.evidence['partition_total']:,}.",
        "",
        "`train/` and `val/` repeat each image three times (one per haze severity)",
        "under sequential renumbering, which destroys the DIOR id:",
        "",
        "```",
        json.dumps(renum.evidence, indent=2),
        "```",
        "",
        f"So only **{len(ids):,} of {inv.evidence['partition_total']:,}** images can",
        "carry annotations. Those are the ones this project uses.",
        "",
        "## Split membership of the aligned subset",
        "",
        "Assigned from `ImageSets/Main`, never from directory names.",
        "",
        "| DIOR split | Aligned images |",
        "|---|---|",
        f"| train | {member.evidence['train']:,} |",
        f"| val | {member.evidence['val']:,} |",
        f"| test | {member.evidence['test']:,} |",
        "",
        f"> Using the release's *directory* split instead would place",
        f"> **{member.evidence['would_leak']:,} DIOR-test images into training** — the",
        "> leakage path `05-experiment-plan.md` lists first.",
        "",
        "## Resulting corpus",
        "",
        "| Condition | Unique images | Source |",
        "|---|---|---|",
        f"| Clear | {len(ids):,} | `test/gt/` (identical across severities) |",
        f"| Fog | {len(ids) * len(SEVERITIES):,} | `test/haze/{{{','.join(SEVERITIES)}}}/` |",
        "| Dark | — | not synthesised; `src/data/degradation.py` is a stub |",
        "",
        "## Anomalies",
        "",
    ]

    dims = next(c for c in checks if c.name == "image_dimensions")
    if dims.passed:
        lines += ["None. Every aligned image is 800x800 and matches its XML.", ""]
    else:
        lines += [
            f"**{dims.evidence['n_xml_mismatch']} image(s) disagree with their XML "
            f"`<size>`**, and {dims.evidence['n_not_800x800']} are not 800x800:",
            "",
            "```",
            *dims.evidence["xml_mismatch"],
            "```",
            "",
            "This matters and is **unresolved**. Labels are normalised against the",
            "XML size, but Ultralytics de-normalises against the actual image. If",
            "the odd render was *resized* from 800x800 the current labels are",
            "correct; if it was *cropped* they are wrong by the size ratio. The two",
            "cases cannot be distinguished without the clear DIOR original, which is",
            "not on disk. Affected images are listed above — decide before training,",
            "or drop them (they are a rounding error in a 2,607-image corpus).",
            "",
        ]

    lines += [
        "## Not recoverable from this release",
        "",
        "- Clear DIOR `JPEGImages/` for the other 20,856 ids — not on disk.",
        "- The mapping from `train/`+`val/` filenames back to DIOR ids. Recovering",
        "  it needs clear DIOR downloaded, then content-matching the `gt/` renders",
        "  against the DIOR originals.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default=None, help="path to paths.yaml")
    parser.add_argument("--out", default=None, help="output directory")
    args = parser.parse_args()

    paths = load_paths(args.config)
    problems = paths.validate()
    if problems:
        for p in problems:
            log.error(p)
        log.error("Source tree is not where configs/paths.yaml says it is. Stopping.")
        return 2

    log.info("checking %s", paths.hazy_dior_root)
    checks = run_all(paths)

    for c in checks:
        (log.info if c.passed else log.error)(
            "%-32s %s  %s", c.name, "PASS" if c.passed else "FAIL", c.detail
        )

    out_dir = ensure_dir(Path(args.out) if args.out else VERIFICATION_DIR)
    (out_dir / "pairing_report.md").write_text(
        render_markdown(paths, checks), encoding="utf-8"
    )
    (out_dir / "pairing_report.json").write_text(
        json.dumps(checks_to_dict(checks), indent=2), encoding="utf-8"
    )
    log.info("wrote %s", out_dir / "pairing_report.md")

    return 0 if all(c.passed for c in checks) else 1


if __name__ == "__main__":
    raise SystemExit(main())
