"""Train a stock YOLO11 HBB detector from a config.

    python scripts/train.py --config configs/train/smoke.yaml
    python scripts/train.py --config configs/train/fog_yolo11n.yaml

No hyperparameters or paths live in this file; everything comes from the config.

HOW MLFLOW LOGGING WORKS HERE
-----------------------------
Metrics and hyperparameters are logged by Ultralytics' OWN MLflow callback, not
by this script. That callback does `mlflow.log_params(dict(trainer.args))` (every
hyperparameter), then per-epoch learning rates, train losses, val losses, mAP50
and mAP50-95, and finally the weights and plots as artifacts.

The one thing it cannot know is provenance: which commit, which config, which
data. So this script opens the MLflow run itself and tags that on. Ultralytics'
callback checks `mlflow.active_run()` and attaches to an existing run rather than
starting its own (see ultralytics/utils/callbacks/mlflow.py), so the result is a
single run carrying both. No metric is logged twice, and no metric is logged from
here.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.data.dior_classes import DIOR_CLASSES  # noqa: E402
from src.data.subset import stratified_subset, write_image_list  # noqa: E402
from src.utils.config import RunConfig, load_run_config  # noqa: E402
from src.utils.logging import get_logger  # noqa: E402
from src.utils.paths import OUTPUT_DIR, REPO_ROOT, dataset_root, ensure_dir  # noqa: E402
from src.utils.seed import git_commit, seed_everything  # noqa: E402

log = get_logger("train")

MLRUNS_DIR = OUTPUT_DIR / "mlruns"
RUNS_DIR = OUTPUT_DIR / "runs"


def build_subset_data_yaml(cfg: RunConfig) -> Path:
    """Write class-stratified train/val image lists plus a data yaml for them."""
    root = dataset_root(cfg.task) / cfg.condition
    out_dir = ensure_dir(dataset_root(cfg.task) / "subsets")

    lists: dict[str, Path] = {}
    for split, n in (cfg.subset or {}).items():
        picks, counts = stratified_subset(root / "images" / split, n=int(n), seed=cfg.seed)
        lists[split] = write_image_list(picks, out_dir / f"{cfg.run_name}_{split}.txt")
        missing = [c for c in DIOR_CLASSES if c not in counts]
        log.info(
            "subset %-5s: %d images, %d/%d classes present",
            split, len(picks), len(counts), len(DIOR_CLASSES),
        )
        if missing:
            log.warning(
                "  %d class(es) absent from the %s subset: %s",
                len(missing), split, ", ".join(missing),
            )

    dst = out_dir / f"{cfg.run_name}.yaml"
    lines = [
        f"# Generated by scripts/train.py for run '{cfg.run_name}'. Do not edit.",
        f"path: {root.resolve().as_posix()}",
        f"train: {lists['train'].resolve().as_posix()}"
        if "train" in lists
        else "train: images/train",
        f"val: {lists['val'].resolve().as_posix()}" if "val" in lists else "val: images/val",
        "test: images/test",
        "",
        "names:",
        *[f"  {i}: {n}" for i, n in enumerate(DIOR_CLASSES)],
    ]
    dst.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return dst


def count_images(data_yaml: Path) -> dict[str, int]:
    """Image count per split, for provenance."""
    import yaml as _yaml

    spec = _yaml.safe_load(data_yaml.read_text(encoding="utf-8"))
    root = Path(spec["path"])
    out: dict[str, int] = {}
    for split in ("train", "val", "test"):
        entry = spec.get(split)
        if not entry:
            continue
        p = Path(entry)
        p = p if p.is_absolute() else root / p
        if p.suffix == ".txt" and p.exists():
            out[split] = len([ln for ln in p.read_text(encoding="utf-8").splitlines() if ln.strip()])
        elif p.is_dir():
            out[split] = len([q for q in p.iterdir() if q.suffix.lower() in {".jpg", ".jpeg", ".png"}])
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True, help="path to a configs/train/*.yaml")
    parser.add_argument("--device", default=None, help="override the config's device")
    parser.add_argument("--epochs", type=int, default=None, help="override the config's epochs")
    args = parser.parse_args()

    cfg = load_run_config(args.config)
    seed_everything(cfg.seed)
    commit = git_commit(short=True)

    # MLflow is configured entirely through the environment, so Ultralytics'
    # callback picks it up without a single tracker call in our own code.
    ensure_dir(MLRUNS_DIR)
    tracking_uri = MLRUNS_DIR.resolve().as_uri()
    os.environ["MLFLOW_TRACKING_URI"] = tracking_uri
    os.environ["MLFLOW_EXPERIMENT_NAME"] = cfg.experiment
    os.environ["MLFLOW_RUN"] = f"{cfg.run_name}-{commit}"

    from ultralytics import YOLO, settings

    if settings.get("mlflow") is not True:
        settings.update({"mlflow": True})
        log.info("enabled Ultralytics' mlflow integration")

    data_yaml = build_subset_data_yaml(cfg) if cfg.subset else cfg.data_yaml
    if not data_yaml.exists():
        log.error("data yaml missing: %s — run scripts/prepare_dataset.py first", data_yaml)
        return 2

    counts = count_images(data_yaml)
    log.info("config     : %s", cfg.path.relative_to(REPO_ROOT))
    log.info("condition  : %s   task: %s", cfg.condition, cfg.task)
    log.info("data       : %s  %s", data_yaml, counts)
    log.info("model      : %s (scale %s)", cfg.model_path.name, cfg.scale)
    log.info("seed       : %s   commit: %s", cfg.seed, commit)
    log.info("mlflow     : %s  experiment=%s", tracking_uri, cfg.experiment)

    train_args = dict(cfg.train)
    if args.device is not None:
        train_args["device"] = args.device
    if args.epochs is not None:
        train_args["epochs"] = args.epochs

    import mlflow  # provenance only — no metrics are logged from this file
    import torch

    mlflow.set_tracking_uri(tracking_uri)
    mlflow.set_experiment(cfg.experiment)

    with mlflow.start_run(run_name=os.environ["MLFLOW_RUN"]):
        import ultralytics

        mlflow.set_tags(
            {
                "git_commit": commit,
                "config": str(cfg.path.relative_to(REPO_ROOT)),
                "condition": cfg.condition,
                "box_format": "hbb" if cfg.task == "detect" else "obb",
                "task": cfg.task,
                "model_cfg": cfg.model_path.name,
                "scale": cfg.scale,
                "ultralytics": ultralytics.__version__,
                "torch": torch.__version__,
                "gpu": torch.cuda.get_device_name(0) if torch.cuda.is_available() else "cpu",
            }
        )
        mlflow.log_params(
            {"seed": cfg.seed, **{f"n_images_{k}": v for k, v in counts.items()}}
        )
        mlflow.log_artifact(str(cfg.path))
        mlflow.log_artifact(str(cfg.model_path))

        model = YOLO(str(cfg.scaled_model()), task=cfg.task)
        model.train(
            data=str(data_yaml),
            project=str(RUNS_DIR),
            name=cfg.run_name,
            exist_ok=True,
            seed=cfg.seed,
            **train_args,
        )

    save_dir = RUNS_DIR / cfg.run_name
    log.info("done. weights: %s", save_dir / "weights" / "best.pt")
    log.info("mlflow ui --backend-store-uri %s", MLRUNS_DIR)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

